name: Scrape data
on:
  schedule:
    - cron: "0 * * * *" # Every hour
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install tq
        run: sudo pip3 install https://github.com/plainas/tq/zipball/stable
      - name: scrape
        run: megekko.sh
        env:
          ORDER_ID: ${{ secrets.ORDER_ID }}
          POSTCODE: ${{ secrets.POSTCODE }}
      - name: commit results
        uses: mikael/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
