name: Scrape data
on:
  schedule:
    - cron: "0 * * * *" # Every hour
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            https://github.com/plainas/tq/zipball/stable
      # - name: install tq
      #   run: pip3 install https://github.com/plainas/tq/zipball/stable
      - name: scrape
        run: megekko.sh
        env:
          ORDER_ID: ${{ secrets.ORDER_ID }}
          POSTCODE: ${{ secrets.POSTCODE }}
      - name: commit results
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
