name: Scrape data
on:
  schedule:
    - cron: "0 * * * *" # Every hour
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install tq
        run: |
          sudo apt-get install python3-setuptools
          sudo -H pip3 install --upgrade pip
          sudo -H pip3 install https://github.com/plainas/tq/zipball/stable
      - name: scrape
        run: megekko.sh
        env:
          ORDER_ID: ${{ secrets.ORDER_ID }}
          POSTCODE: ${{ secrets.POSTCODE }}
      - name: commit results
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
